### ISSUE TITLE
Random images for &heresy command

### ISSUE THREAD

**Issue by OmnissiahZelos** [Nikey646/ConstructionBot#1]
Please make the picture of choice a random one for fun and variety :)

https://1d4chan.org/images/thumb/9/90/Heresy_vein-popping.png/300px-Heresy_vein-popping.png
http://i2.kym-cdn.com/photos/images/facebook/000/706/073/4cf.jpg
https://s-media-cache-ak0.pinimg.com/736x/cb/dc/70/cbdc70cf819a13ac49834ee7849e0beb--warhammer--warhammer-k-funny.jpg
http://imgur.com/0BXvcdE
http://www.funnyjunk.com/channel/warhammer40k/When+i+see+some+heresy/nBbqLaO#39f768_6265739
http://imgur.com/SCIa8Im
http://whec-assets-live.s3.amazonaws.com/2015/01/45566_33166738b192d6669723dcea553b952a.jpg
http://imgur.com/VjFWzqI
http://imgur.com/TkN4OAa
http://imgur.com/SCIa8Im
https://cdn.discordapp.com/attachments/231518135231053825/332135617846575108/399.png
http://knowyourmeme.com/photos/1207464-heresy
http://i901.photobucket.com/albums/ac217/LordAbbendis/Notsure_zps4a355057.jpg

**Comment by OmnissiahZelos** [comment]
MORE!
https://pbs.twimg.com/media/BrFtrgGCEAAUo3B.jpg
https://s-media-cache-ak0.pinimg.com/originals/40/a6/35/40a63527a6d152febbe1c816972aa9ec.jpg
http://i2.kym-cdn.com/photos/images/original/000/706/295/928.jpg
http://imgur.com/b6zIbyj
http://imgur.com/QCtRAd9
http://i2.kym-cdn.com/photos/images/facebook/000/706/087/872.jpg
https://qph.ec.quoracdn.net/main-qimg-038564e169946aea586d8eb927b3f1a5-c
http://imgur.com/pWN7wb4

**Comment by Nikey646** [comment]
Okay, this has been added.

Couldn't add http://i901.photobucket.com/albums/ac217/LordAbbendis/Notsure_zps4a355057.jpg , because the image appears to be dead (Rate limiting?)

If you want to add anymore images, just make a PR editing this [file](https://github.com/Nikey646/ConstructionBot/blob/master/Data/heresy.json)
